export const ActionTypes ={
       //PRODUCTS
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    // USER AUTENTICATION
  SIGNIN_SUCCESS : 'SIGNIN_SUCCESS',
 SIGNOUT_SUCCESS : 'SIGNOUT_SUCCESS',
 SET_AUTHENTICATION :'SET_AUTHENTICATION',

 // CART 
 ADD_TO_CART:'ADD_TO_CART',
 REMOVE_FROM_CART:'REMOVE_FROM_CART',

 SET_CART_ITEMS : 'SET_CART_ITEMS',
 FETCH_CART_ITEMs:'FETCH_CART_ITEMs',
 INCREMENT_ITEM_QUANTITY :'INCREMENT_ITEM_QUANTITY',
 DECREMENT_ITEM_QUANTITY:'DECREMENT_ITEM_QUANTITY',

 SET_SEARCH_RESULTS:'SET_SEARCH_RESULTS',
 SET_CATEGORIES:'SET_CATEGORIES'
}